version: "2"
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  consul:
      image: progrium/consul
      ports:
        - "8500:8500"
      environment:
        - CONSUL_BIND_INTERFACE=eth0
      command: ["-server", "-bootstrap", "-ui-dir", "/ui"]

  ves-hv-collector:
    image: onap/ves-hv-collector
#    build:
#      context: hv-collector-main
#      dockerfile: Dockerfile
    ports:
      - "6061:6061/tcp"
    depends_on:
      - kafka
      - consul
    volumes:
      - ./ssl/:/etc/ves-hv/

  xnf-simulator:
    image: onap/ves-hv-collector-client-simulator
#    build:
#      context: hv-collector-client-simulator
#      dockerfile: Dockerfile
    ports:
      - "8000:5000/tcp"
    depends_on:
      - ves-hv-collector
    volumes:
      - ./ssl/:/etc/ves-hv/

  dcae-app-simulator:
    image: onap/ves-hv-collector-dcae-simulator
#    build:
#      context: hv-collector-dcae-app-simulator
#      dockerfile: Dockerfile
    ports:
      - "8100:5000/tcp"
    depends_on:
      - kafka
