version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  veshvcollector:
    build:
      context: hv-collector-main
      dockerfile: Dockerfile
    ports:
      - "6061:6061/tcp"
    depends_on:
      - kafka
    volumes:
      - ./ssl/:/etc/ves-hv/
  xnfsimulator:
    build:
      context: hv-collector-client-simulator
      dockerfile: Dockerfile
    depends_on:
      - veshvcollector
    volumes:
      - ./ssl/:/etc/ves-hv/